version: "3.9"
services:
  next-app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
    command: >
      sh -c 'if [ "$NODE_ENV" = "production" ]; then npm start; else npm run dev; fi'
